version: '3'

include:
  - path:
    - ./docker/database/database.yaml

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    image: boilerplate_develop_api
    container_name: boilerplate_develop_api
    volumes:
      - .:/code
      - /code/node_modules
    command: pnpm start:dev:api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis